// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission4.Models;

namespace Mission4.Migrations
{
    [DbContext(typeof(MovieApplicationContext))]
    [Migration("20220126050146_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission4.Models.ApplicationResponse", b =>
                {
                    b.Property<int>("ApplicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("ApplicationID");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            ApplicationID = 1,
                            Category = "Action",
                            Director = "Doug Liman",
                            Edited = false,
                            LentTo = "",
                            Notes = "Awesome Movie!",
                            Rating = "PG-13",
                            Title = "Jason Bourne: Bourne Identity",
                            Year = 2002
                        },
                        new
                        {
                            ApplicationID = 2,
                            Category = "Sports Drama",
                            Director = "Gavin O'Conner",
                            Edited = false,
                            LentTo = "",
                            Notes = "Watch alone, makes me emotional",
                            Rating = "PG-13",
                            Title = "Warrior",
                            Year = 2011
                        },
                        new
                        {
                            ApplicationID = 3,
                            Category = "Science Fiction",
                            Director = "Denis Villeneuve",
                            Edited = false,
                            LentTo = "",
                            Notes = "Super Awesome Movie, should read the book too...",
                            Rating = "PG-13",
                            Title = "Dune",
                            Year = 2021
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
